[2023-01-17T12:04:49.142+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sample_data_etl_v4.sample_data_precheck scheduled__2023-01-17T07:00:00+00:00 [queued]>
[2023-01-17T12:04:49.165+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sample_data_etl_v4.sample_data_precheck scheduled__2023-01-17T07:00:00+00:00 [queued]>
[2023-01-17T12:04:49.166+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T12:04:49.166+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T12:04:49.202+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T12:04:49.442+0000] {taskinstance.py:1304} INFO - Executing <Task(MsSqlOperator): sample_data_precheck> on 2023-01-17 07:00:00+00:00
[2023-01-17T12:04:49.458+0000] {standard_task_runner.py:55} INFO - Started process 3508 to run task
[2023-01-17T12:04:49.461+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sample_data_etl_v4', 'sample_data_precheck', 'scheduled__2023-01-17T07:00:00+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/test_table_insert.py', '--cfg-path', '/tmp/tmp1patpfvt']
[2023-01-17T12:04:49.463+0000] {standard_task_runner.py:83} INFO - Job 447: Subtask sample_data_precheck
[2023-01-17T12:04:49.731+0000] {task_command.py:389} INFO - Running <TaskInstance: sample_data_etl_v4.sample_data_precheck scheduled__2023-01-17T07:00:00+00:00 [running]> on host c7f1bfaaf748
[2023-01-17T12:04:50.142+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=StepanovLM@eurosib.biz
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sample_data_etl_v4
AIRFLOW_CTX_TASK_ID=sample_data_precheck
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-17T07:00:00+00:00
[2023-01-17T12:04:50.143+0000] {sql.py:253} INFO - Executing: select getDate() as nowdate
[2023-01-17T12:04:50.156+0000] {base.py:73} INFO - Using connection ID 'tsxdvp' for task execution.
[2023-01-17T12:04:50.531+0000] {base.py:73} INFO - Using connection ID 'tsxdvp' for task execution.
[2023-01-17T12:04:50.588+0000] {sql.py:364} INFO - Running statement: select getDate() as nowdate, parameters: None
[2023-01-17T12:04:50.632+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'datetime.datetime' object has no attribute '__module__'
[2023-01-17T12:04:50.656+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=sample_data_etl_v4, task_id=sample_data_precheck, execution_date=20230117T070000, start_date=20230117T120449, end_date=20230117T120450
[2023-01-17T12:04:50.844+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 447 for task sample_data_precheck ('datetime.datetime' object has no attribute '__module__'; 3508)
[2023-01-17T12:04:50.881+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T12:04:51.009+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
