[2023-01-17T10:00:03.012+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sample_data_etl_v2.sample_data_precheck scheduled__2023-01-17T09:00:00+00:00 [queued]>
[2023-01-17T10:00:03.021+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sample_data_etl_v2.sample_data_precheck scheduled__2023-01-17T09:00:00+00:00 [queued]>
[2023-01-17T10:00:03.021+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T10:00:03.022+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T10:00:03.045+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T10:00:03.218+0000] {taskinstance.py:1304} INFO - Executing <Task(MsSqlOperator): sample_data_precheck> on 2023-01-17 09:00:00+00:00
[2023-01-17T10:00:03.222+0000] {standard_task_runner.py:55} INFO - Started process 9666 to run task
[2023-01-17T10:00:03.225+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sample_data_etl_v2', 'sample_data_precheck', 'scheduled__2023-01-17T09:00:00+00:00', '--job-id', '381', '--raw', '--subdir', 'DAGS_FOLDER/test_table_insert.py', '--cfg-path', '/tmp/tmp7f4rf5pg']
[2023-01-17T10:00:03.227+0000] {standard_task_runner.py:83} INFO - Job 381: Subtask sample_data_precheck
[2023-01-17T10:00:03.358+0000] {task_command.py:389} INFO - Running <TaskInstance: sample_data_etl_v2.sample_data_precheck scheduled__2023-01-17T09:00:00+00:00 [running]> on host c7f1bfaaf748
[2023-01-17T10:00:03.514+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=StepanovLM@eurosib.biz
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sample_data_etl_v2
AIRFLOW_CTX_TASK_ID=sample_data_precheck
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T09:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-17T09:00:00+00:00
[2023-01-17T10:00:03.515+0000] {sql.py:253} INFO - Executing: use CarInfo; select getDate()
[2023-01-17T10:00:03.524+0000] {base.py:73} INFO - Using connection ID 'tsxdvp' for task execution.
[2023-01-17T10:00:03.826+0000] {base.py:73} INFO - Using connection ID 'tsxdvp' for task execution.
[2023-01-17T10:00:05.016+0000] {sql.py:364} INFO - Running statement: use CarInfo; select getDate(), parameters: None
[2023-01-17T10:00:05.033+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'datetime.datetime' object has no attribute '__module__'
[2023-01-17T10:00:05.079+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=sample_data_etl_v2, task_id=sample_data_precheck, execution_date=20230117T090000, start_date=20230117T100003, end_date=20230117T100005
[2023-01-17T10:00:05.158+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 381 for task sample_data_precheck ('datetime.datetime' object has no attribute '__module__'; 9666)
[2023-01-17T10:00:05.168+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T10:00:05.191+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
