[2023-01-17T09:03:13.921+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sample_data_etl_v2.sample_data_precheck scheduled__2023-01-17T03:00:00+00:00 [queued]>
[2023-01-17T09:03:13.930+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sample_data_etl_v2.sample_data_precheck scheduled__2023-01-17T03:00:00+00:00 [queued]>
[2023-01-17T09:03:13.931+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T09:03:13.931+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T09:03:13.949+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T09:03:14.172+0000] {taskinstance.py:1304} INFO - Executing <Task(MsSqlOperator): sample_data_precheck> on 2023-01-17 03:00:00+00:00
[2023-01-17T09:03:14.176+0000] {standard_task_runner.py:55} INFO - Started process 4277 to run task
[2023-01-17T09:03:14.180+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sample_data_etl_v2', 'sample_data_precheck', 'scheduled__2023-01-17T03:00:00+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/test_table_insert.py', '--cfg-path', '/tmp/tmp5axk6x4q']
[2023-01-17T09:03:14.538+0000] {standard_task_runner.py:83} INFO - Job 374: Subtask sample_data_precheck
[2023-01-17T09:03:22.845+0000] {task_command.py:389} INFO - Running <TaskInstance: sample_data_etl_v2.sample_data_precheck scheduled__2023-01-17T03:00:00+00:00 [running]> on host c7f1bfaaf748
[2023-01-17T09:03:48.992+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=StepanovLM@eurosib.biz
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sample_data_etl_v2
AIRFLOW_CTX_TASK_ID=sample_data_precheck
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T03:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-17T03:00:00+00:00
[2023-01-17T09:03:59.841+0000] {sql.py:253} INFO - Executing: use CarInfo; select getDate()
[2023-01-17T09:04:00.033+0000] {base.py:73} INFO - Using connection ID 'tsxdvp' for task execution.
[2023-01-17T09:04:46.043+0000] {base.py:73} INFO - Using connection ID 'tsxdvp' for task execution.
[2023-01-17T09:05:06.442+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 647, in pymssql._pymssql.connect
  File "src/pymssql/_mssql.pyx", line 2109, in pymssql._mssql.connect
  File "src/pymssql/_mssql.pyx", line 701, in pymssql._mssql.MSSQLConnection.__init__
  File "src/pymssql/_mssql.pyx", line 1818, in pymssql._mssql.maybe_raise_MSSQLDatabaseException
  File "src/pymssql/_mssql.pyx", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (172.30.6.32)\nNet-Lib error during No route to host (113)\nDB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (172.30.6.32)\nNet-Lib error during No route to host (113)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 331, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 102, in get_conn
    port=conn.port,
  File "src/pymssql/_pymssql.pyx", line 653, in pymssql._pymssql.connect
pymssql._pymssql.OperationalError: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (172.30.6.32)\nNet-Lib error during No route to host (113)\nDB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (172.30.6.32)\nNet-Lib error during No route to host (113)\n')
[2023-01-17T09:05:07.337+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=sample_data_etl_v2, task_id=sample_data_precheck, execution_date=20230117T030000, start_date=20230117T090313, end_date=20230117T090507
[2023-01-17T09:05:09.926+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 374 for task sample_data_precheck ((20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (172.30.6.32)\nNet-Lib error during No route to host (113)\nDB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (172.30.6.32)\nNet-Lib error during No route to host (113)\n'); 4277)
[2023-01-17T09:05:16.541+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T09:05:18.781+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
