[2023-01-17T12:00:10.343+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sample_data_etl_v3.sample_data_precheck scheduled__2023-01-17T11:00:00+00:00 [queued]>
[2023-01-17T12:00:11.748+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: sample_data_etl_v3.sample_data_precheck scheduled__2023-01-17T11:00:00+00:00 [queued]>
[2023-01-17T12:00:11.749+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T12:00:11.749+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-17T12:00:11.750+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-17T12:00:12.432+0000] {taskinstance.py:1304} INFO - Executing <Task(MsSqlOperator): sample_data_precheck> on 2023-01-17 11:00:00+00:00
[2023-01-17T12:00:12.437+0000] {standard_task_runner.py:55} INFO - Started process 3061 to run task
[2023-01-17T12:00:12.441+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sample_data_etl_v3', 'sample_data_precheck', 'scheduled__2023-01-17T11:00:00+00:00', '--job-id', '439', '--raw', '--subdir', 'DAGS_FOLDER/test_table_insert.py', '--cfg-path', '/tmp/tmp9tn9hn4i']
[2023-01-17T12:00:12.444+0000] {standard_task_runner.py:83} INFO - Job 439: Subtask sample_data_precheck
[2023-01-17T12:00:16.593+0000] {task_command.py:389} INFO - Running <TaskInstance: sample_data_etl_v3.sample_data_precheck scheduled__2023-01-17T11:00:00+00:00 [running]> on host c7f1bfaaf748
[2023-01-17T12:00:18.923+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=StepanovLM@eurosib.biz
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sample_data_etl_v3
AIRFLOW_CTX_TASK_ID=sample_data_precheck
AIRFLOW_CTX_EXECUTION_DATE=2023-01-17T11:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-17T11:00:00+00:00
[2023-01-17T12:00:18.924+0000] {sql.py:253} INFO - Executing: select getDate() as nowdate
[2023-01-17T12:00:18.934+0000] {base.py:73} INFO - Using connection ID 'tsxdvp' for task execution.
[2023-01-17T12:00:19.199+0000] {base.py:73} INFO - Using connection ID 'tsxdvp' for task execution.
[2023-01-17T12:00:22.897+0000] {sql.py:364} INFO - Running statement: select getDate() as nowdate, parameters: None
[2023-01-17T12:00:22.914+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'datetime.datetime' object has no attribute '__module__'
[2023-01-17T12:00:23.052+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=sample_data_etl_v3, task_id=sample_data_precheck, execution_date=20230117T110000, start_date=20230117T120010, end_date=20230117T120023
[2023-01-17T12:00:23.197+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 439 for task sample_data_precheck ('datetime.datetime' object has no attribute '__module__'; 3061)
[2023-01-17T12:00:23.220+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-17T12:00:23.243+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
